[tool.poetry]
name = "repl_python3_elite-qualifier"
version = "0.1.0"
description = ""
authors = ["Spe4738 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pytz = "^2021.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
